server:
  host: "localhost"
  port: 8080
  uiPort: 3000
  shutdownTimeout: 10s
  readTimeout: 5s
  writeTimeout: 5s
  enableCORS: true
  allowedOrigins:
    - "http://localhost:3000"
    - "http://localhost:8080"

feeds:
  - name: "binance"
    type: "websocket"
    url: "wss://stream.binance.com:9443/ws"
    subscriptions:
      - "btcusdt@depth"
      - "ethusdt@depth"
    symbols:
      - "BTCUSDT"
      - "ETHUSDT"
    apiKey: ""
    apiSecret: ""
  - name: "coinbase"
    type: "websocket"
    url: "wss://ws-feed.pro.coinbase.com"
    subscriptions:
      - "level2"
    symbols:
      - "BTC-USD"
      - "ETH-USD"
    apiKey: ""
    apiSecret: ""
  - name: "kraken"
    type: "websocket"
    url: "wss://ws.kraken.com"
    subscriptions:
      - "book"
    symbols:
      - "XBT/USD"
      - "ETH/USD"
    apiKey: ""
    apiSecret: ""
  - name: "nasdaq"
    type: "stock"
    url: "https://query1.finance.yahoo.com/v7/finance/quote"
    symbols:
      - "AAPL"
      - "MSFT"
      - "GOOGL"
      - "AMZN"
      - "TSLA"
    apiKey: ""
    apiSecret: ""
  - name: "nyse"
    type: "stock"
    url: "https://query1.finance.yahoo.com/v7/finance/quote"
    symbols:
      - "JPM"
      - "JNJ"
      - "V"
      - "PG"
      - "UNH"
    apiKey: ""
    apiSecret: ""
  - name: "nse"
    type: "stock"
    url: "https://www.alphavantage.co/query"
    symbols:
      - "RELIANCE.BSE"
      - "TCS.BSE"
      - "HDFCBANK.BSE"
      - "INFY.BSE"
      - "HINDUNILVR.BSE"
    apiKey: "YOUR_ALPHA_VANTAGE_API_KEY"
    apiSecret: ""
  - name: "bse"
    type: "stock"
    url: "https://www.alphavantage.co/query"
    symbols:
      - "RELIANCE.BSE"
      - "TCS.BSE"
      - "HDFCBANK.BSE"
      - "INFY.BSE"
      - "HINDUNILVR.BSE"
    apiKey: "YOUR_ALPHA_VANTAGE_API_KEY"
    apiSecret: ""
  - name: "sp500"
    type: "stock"
    url: "https://query1.finance.yahoo.com/v7/finance/quote"
    symbols:
      - "^GSPC"
    apiKey: ""
    apiSecret: ""
  - name: "dow"
    type: "stock"
    url: "https://query1.finance.yahoo.com/v7/finance/quote"
    symbols:
      - "^DJI"
    apiKey: ""
    apiSecret: ""

fix:
  host: "localhost"
  port: 9876
  username: "velocimex"
  password: "password"
  timeout: 30s
  sender_comp_id: "VELOCIMEX"
  target_comp_id: "EXCHANGE"
  begin_string: "FIX.4.4"
  heart_bt_int: 30
  reset_seq_num: false
  default_order_type: "1"
  default_time_in_force: "1"
  use_ssl: false
  cert_file: ""
  key_file: ""
  ca_file: ""
  log_heartbeats: false
  log_messages: true
  log_file: "fix.log"

risk:
  enabled: true
  update_interval: 1s
  alert_thresholds:
    max_position_size: 10000.0
    max_portfolio_value: 100000.0
    max_daily_loss: 5000.0
    max_drawdown: 0.1
    max_concentration: 0.2
    max_leverage: 2.0
    stop_loss_percentage: 0.05
    take_profit_percentage: 0.1
  auto_stop_loss: true
  auto_take_profit: true
  max_open_positions: 10
  position_sizing_mode: "PERCENTAGE"
  default_position_size: 0.02
  risk_free_rate: 0.02
  lookback_period: 30

strategies:
  arbitrage:
    name: "Cross-Exchange Arbitrage"
    symbols:
      - "BTC/USD"
      - "ETH/USD"
    exchanges:
      - "binance"
      - "coinbase"
      - "kraken"
    updateInterval: 5s
    minimumSpread: 0.1
    maxSlippage: 0.05
    minProfitThreshold: 0.2
    maxExecutionLatency: 100
    simultaneousExchanges: 2
    exchangeFees:
      binance: 0.001
      coinbase: 0.005
      kraken: 0.0026
    riskLimit: 1000.0

simulation:
  paperTrading:
    enabled: true
    initialBalance:
      USD: 100000.0
      BTC: 10.0
      ETH: 100.0
    latencySimulation: true
    baseLatency: 20
    randomLatency: 10
    slippageModel: "fixed"
    fixedSlippage: 0.02
    exchangeFees:
      binance: 0.001
      coinbase: 0.005
      kraken: 0.0026
